### ISSUE TITLE
Disable CORS does not work

### ISSUE THREAD

**Issue by vadym-kovryzhkin** [internap/python-mockserver-friendly-client#17]
I am running mock-server with java: 
```
java -DenableCORSForAPI=false -jar "mockserver-netty-5.3.0-jar-with-dependencies.jar" -serverPort 1080 -proxyPort 1090
```
But always see the X-CORS header, along with the default headers that are added when CORS is switched on, and all of my headers specified in the expectation are missing.
`X-CORS: MockServer CORS support enabled by default, to disable ConfigurationProperties.enableCORSForAPI(false) or -Dmockserver.disableCORS=false`

**Comment by lindycoder** [comment]
This does not seem to be related to the python client but rather the server tool, please report to
https://github.com/jamesdbloom/mockserver
